name: Docker Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "ghcr.io/v0l/nostr-rs-relay:latest"
          platforms: "linux/amd64"
          cache-from: type=gha
          cache-to: type=gha,mode=max